// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package model

import (
	"context"
)

const listGamesBySeason = `-- name: ListGamesBySeason :many
SELECT
    g.game_date,
    g.game_time,
    substr(g.game_date, 6, 2) AS month,
    ht.name AS home_team_name,
    at2.name AS away_team_name,
    COALESCE(NULLIF(v.stadium || ', ' || v.city, ', ' || v.city), v.city, '') AS venue_display,
    COALESCE(v.lat, 0.0) AS venue_lat,
    COALESCE(v.lon, 0.0) AS venue_lon,
    COALESCE(NULLIF(l.short_name, ''), l.name) AS league_short,
    l.name AS league_long,
    g.league_id,
    g.position,
    g.referee_fee,
    g.travel_costs,
    g.km_driven,
    g.exhibition
FROM games g
JOIN teams ht ON g.home_team_id = ht.id
JOIN teams at2 ON g.away_team_id = at2.id
LEFT JOIN venues v ON g.venue_id = v.id
JOIN leagues l ON g.league_id = l.id
WHERE substr(g.game_date, 1, 4) = ?
ORDER BY g.game_date
`

type ListGamesBySeasonRow struct {
	GameDate     string
	GameTime     string
	Month        string
	HomeTeamName string
	AwayTeamName string
	VenueDisplay string
	VenueLat     float64
	VenueLon     float64
	LeagueShort  string
	LeagueLong   string
	LeagueID     int64
	Position     string
	RefereeFee   float64
	TravelCosts  float64
	KmDriven     int64
	Exhibition   int64
}

func (q *Queries) ListGamesBySeason(ctx context.Context, gameDate string) ([]ListGamesBySeasonRow, error) {
	rows, err := q.db.QueryContext(ctx, listGamesBySeason, gameDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGamesBySeasonRow
	for rows.Next() {
		var i ListGamesBySeasonRow
		if err := rows.Scan(
			&i.GameDate,
			&i.GameTime,
			&i.Month,
			&i.HomeTeamName,
			&i.AwayTeamName,
			&i.VenueDisplay,
			&i.VenueLat,
			&i.VenueLon,
			&i.LeagueShort,
			&i.LeagueLong,
			&i.LeagueID,
			&i.Position,
			&i.RefereeFee,
			&i.TravelCosts,
			&i.KmDriven,
			&i.Exhibition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesFull = `-- name: ListGamesFull :many
SELECT
    g.game_date,
    substr(g.game_date, 1, 4) AS year,
    g.position,
    g.league_id,
    COALESCE(NULLIF(l.short_name, ''), l.name) AS league_short,
    g.referee_fee,
    g.travel_costs,
    g.km_driven,
    COALESCE(NULLIF(v.stadium || ', ' || v.city, ', ' || v.city), v.city, '') AS venue_display,
    COALESCE(v.lat, 0.0) AS venue_lat,
    COALESCE(v.lon, 0.0) AS venue_lon
FROM games g
JOIN leagues l ON g.league_id = l.id
LEFT JOIN venues v ON g.venue_id = v.id
ORDER BY g.game_date
`

type ListGamesFullRow struct {
	GameDate     string
	Year         string
	Position     string
	LeagueID     int64
	LeagueShort  string
	RefereeFee   float64
	TravelCosts  float64
	KmDriven     int64
	VenueDisplay string
	VenueLat     float64
	VenueLon     float64
}

func (q *Queries) ListGamesFull(ctx context.Context) ([]ListGamesFullRow, error) {
	rows, err := q.db.QueryContext(ctx, listGamesFull)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGamesFullRow
	for rows.Next() {
		var i ListGamesFullRow
		if err := rows.Scan(
			&i.GameDate,
			&i.Year,
			&i.Position,
			&i.LeagueID,
			&i.LeagueShort,
			&i.RefereeFee,
			&i.TravelCosts,
			&i.KmDriven,
			&i.VenueDisplay,
			&i.VenueLat,
			&i.VenueLon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
