// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package model

import (
	"context"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (
    game_date, game_time, home_team_id, away_team_id, venue_id,
    league_id, position, referee_fee, travel_costs, km_driven,
    exhibition, remarks, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    datetime('now', 'localtime'), datetime('now', 'localtime'))
RETURNING id, game_date, game_time, home_team_id, away_team_id, venue_id, league_id, position, referee_fee, travel_costs, km_driven, exhibition, remarks, created_at, updated_at
`

type CreateGameParams struct {
	GameDate    string
	GameTime    string
	HomeTeamID  int64
	AwayTeamID  int64
	VenueID     int64
	LeagueID    int64
	Position    string
	RefereeFee  float64
	TravelCosts float64
	KmDriven    int64
	Exhibition  int64
	Remarks     string
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.GameDate,
		arg.GameTime,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.VenueID,
		arg.LeagueID,
		arg.Position,
		arg.RefereeFee,
		arg.TravelCosts,
		arg.KmDriven,
		arg.Exhibition,
		arg.Remarks,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.GameDate,
		&i.GameTime,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.VenueID,
		&i.LeagueID,
		&i.Position,
		&i.RefereeFee,
		&i.TravelCosts,
		&i.KmDriven,
		&i.Exhibition,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM games WHERE id = ?
`

func (q *Queries) DeleteGame(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGame, id)
	return err
}

const getGame = `-- name: GetGame :one
SELECT id, game_date, game_time,
    home_team_id, away_team_id, venue_id, league_id, position,
    referee_fee, travel_costs, km_driven, exhibition, remarks,
    created_at, updated_at
FROM games
WHERE id = ?
`

func (q *Queries) GetGame(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.GameDate,
		&i.GameTime,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.VenueID,
		&i.LeagueID,
		&i.Position,
		&i.RefereeFee,
		&i.TravelCosts,
		&i.KmDriven,
		&i.Exhibition,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGames = `-- name: ListGames :many
SELECT
    g.id, g.game_date, g.game_time,
    g.home_team_id, g.away_team_id, g.venue_id, g.league_id, g.position,
    g.referee_fee, g.travel_costs, g.km_driven, g.exhibition, g.remarks,
    g.created_at, g.updated_at,
    ht.name AS home_team_name,
    at2.name AS away_team_name,
    COALESCE(v.city, '') AS venue_city, COALESCE(v.stadium, '') AS venue_stadium,
    l.name AS league_name, l.short_name AS league_short_name
FROM games g
JOIN teams ht ON g.home_team_id = ht.id
JOIN teams at2 ON g.away_team_id = at2.id
LEFT JOIN venues v ON g.venue_id = v.id
JOIN leagues l ON g.league_id = l.id
ORDER BY g.game_date DESC, g.game_time ASC
`

type ListGamesRow struct {
	ID              int64
	GameDate        string
	GameTime        string
	HomeTeamID      int64
	AwayTeamID      int64
	VenueID         int64
	LeagueID        int64
	Position        string
	RefereeFee      float64
	TravelCosts     float64
	KmDriven        int64
	Exhibition      int64
	Remarks         string
	CreatedAt       string
	UpdatedAt       string
	HomeTeamName    string
	AwayTeamName    string
	VenueCity       string
	VenueStadium    string
	LeagueName      string
	LeagueShortName string
}

func (q *Queries) ListGames(ctx context.Context) ([]ListGamesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGamesRow
	for rows.Next() {
		var i ListGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.GameDate,
			&i.GameTime,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.VenueID,
			&i.LeagueID,
			&i.Position,
			&i.RefereeFee,
			&i.TravelCosts,
			&i.KmDriven,
			&i.Exhibition,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HomeTeamName,
			&i.AwayTeamName,
			&i.VenueCity,
			&i.VenueStadium,
			&i.LeagueName,
			&i.LeagueShortName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasons = `-- name: ListSeasons :many
SELECT DISTINCT substr(game_date, 1, 4) AS season
FROM games
ORDER BY season DESC
`

func (q *Queries) ListSeasons(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var season string
		if err := rows.Scan(&season); err != nil {
			return nil, err
		}
		items = append(items, season)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGame = `-- name: UpdateGame :exec
UPDATE games
SET game_date = ?, game_time = ?, home_team_id = ?, away_team_id = ?,
    venue_id = ?, league_id = ?, position = ?, referee_fee = ?,
    travel_costs = ?, km_driven = ?, exhibition = ?, remarks = ?,
    updated_at = datetime('now', 'localtime')
WHERE id = ?
`

type UpdateGameParams struct {
	GameDate    string
	GameTime    string
	HomeTeamID  int64
	AwayTeamID  int64
	VenueID     int64
	LeagueID    int64
	Position    string
	RefereeFee  float64
	TravelCosts float64
	KmDriven    int64
	Exhibition  int64
	Remarks     string
	ID          int64
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) error {
	_, err := q.db.ExecContext(ctx, updateGame,
		arg.GameDate,
		arg.GameTime,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.VenueID,
		arg.LeagueID,
		arg.Position,
		arg.RefereeFee,
		arg.TravelCosts,
		arg.KmDriven,
		arg.Exhibition,
		arg.Remarks,
		arg.ID,
	)
	return err
}
