// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leagues.sql

package model

import (
	"context"
)

const createLeague = `-- name: CreateLeague :one
INSERT INTO leagues (name, short_name, sorter, remarks, created_at, updated_at)
VALUES (?, ?, ?, ?, datetime('now', 'localtime'), datetime('now', 'localtime'))
RETURNING id, name, short_name, sorter, remarks, created_at, updated_at
`

type CreateLeagueParams struct {
	Name      string
	ShortName string
	Sorter    int64
	Remarks   string
}

func (q *Queries) CreateLeague(ctx context.Context, arg CreateLeagueParams) (League, error) {
	row := q.db.QueryRowContext(ctx, createLeague,
		arg.Name,
		arg.ShortName,
		arg.Sorter,
		arg.Remarks,
	)
	var i League
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Sorter,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLeague = `-- name: DeleteLeague :exec
DELETE FROM leagues WHERE id = ?
`

func (q *Queries) DeleteLeague(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLeague, id)
	return err
}

const getLeague = `-- name: GetLeague :one
SELECT id, name, short_name, sorter, remarks, created_at, updated_at
FROM leagues
WHERE id = ?
`

func (q *Queries) GetLeague(ctx context.Context, id int64) (League, error) {
	row := q.db.QueryRowContext(ctx, getLeague, id)
	var i League
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Sorter,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLeagues = `-- name: ListLeagues :many
SELECT id, name, short_name, sorter, remarks, created_at, updated_at
FROM leagues
ORDER BY sorter, name
`

func (q *Queries) ListLeagues(ctx context.Context) ([]League, error) {
	rows, err := q.db.QueryContext(ctx, listLeagues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []League
	for rows.Next() {
		var i League
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortName,
			&i.Sorter,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLeague = `-- name: UpdateLeague :exec
UPDATE leagues
SET name = ?, short_name = ?, sorter = ?, remarks = ?, updated_at = datetime('now', 'localtime')
WHERE id = ?
`

type UpdateLeagueParams struct {
	Name      string
	ShortName string
	Sorter    int64
	Remarks   string
	ID        int64
}

func (q *Queries) UpdateLeague(ctx context.Context, arg UpdateLeagueParams) error {
	_, err := q.db.ExecContext(ctx, updateLeague,
		arg.Name,
		arg.ShortName,
		arg.Sorter,
		arg.Remarks,
		arg.ID,
	)
	return err
}
