// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package model

type Game struct {
	ID          int64
	GameDate    string
	GameTime    string
	HomeTeamID  int64
	AwayTeamID  int64
	VenueID     int64
	LeagueID    int64
	Position    string
	RefereeFee  float64
	TravelCosts float64
	KmDriven    int64
	Exhibition  int64
	Remarks     string
	CreatedAt   string
	UpdatedAt   string
}

type League struct {
	ID        int64
	Name      string
	ShortName string
	Sorter    int64
	Remarks   string
	CreatedAt string
	UpdatedAt string
}

type Position struct {
	Position string
	Long     string
	Sorter   int64
}

type Team struct {
	ID        int64
	Name      string
	State     string
	IsActive  int64
	Remarks   string
	CreatedAt string
	UpdatedAt string
}

type Venue struct {
	ID        int64
	City      string
	ShortName string
	Stadium   string
	Lat       float64
	Lon       float64
	CreatedAt string
	UpdatedAt string
}
