// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: positions.sql

package model

import (
	"context"
)

const getAllPositions = `-- name: GetAllPositions :many
SELECT position, long, sorter
FROM positions
ORDER BY sorter
`

func (q *Queries) GetAllPositions(ctx context.Context) ([]Position, error) {
	rows, err := q.db.QueryContext(ctx, getAllPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(&i.Position, &i.Long, &i.Sorter); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
