// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package model

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, state, is_active, remarks, created_at, updated_at)
VALUES (?, ?, ?, ?, datetime('now', 'localtime'), datetime('now', 'localtime'))
RETURNING id, name, state, is_active, remarks, created_at, updated_at
`

type CreateTeamParams struct {
	Name     string
	State    string
	IsActive int64
	Remarks  string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam,
		arg.Name,
		arg.State,
		arg.IsActive,
		arg.Remarks,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.State,
		&i.IsActive,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = ?
`

func (q *Queries) DeleteTeam(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTeam, id)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, state, is_active, remarks, created_at, updated_at
FROM teams
WHERE id = ?
`

func (q *Queries) GetTeam(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.State,
		&i.IsActive,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, state, is_active, remarks, created_at, updated_at
FROM teams
ORDER BY name
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.State,
			&i.IsActive,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :exec
UPDATE teams
SET name = ?, state = ?, is_active = ?, remarks = ?, updated_at = datetime('now', 'localtime')
WHERE id = ?
`

type UpdateTeamParams struct {
	Name     string
	State    string
	IsActive int64
	Remarks  string
	ID       int64
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) error {
	_, err := q.db.ExecContext(ctx, updateTeam,
		arg.Name,
		arg.State,
		arg.IsActive,
		arg.Remarks,
		arg.ID,
	)
	return err
}
