// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venues.sql

package model

import (
	"context"
)

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (city, stadium, lat, lon)
VALUES (?, ?, ?, ?)
RETURNING id, city, stadium, lat, lon, created_at, updated_at
`

type CreateVenueParams struct {
	City    string
	Stadium string
	Lat     float64
	Lon     float64
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRowContext(ctx, createVenue,
		arg.City,
		arg.Stadium,
		arg.Lat,
		arg.Lon,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.City,
		&i.Stadium,
		&i.Lat,
		&i.Lon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVenue = `-- name: DeleteVenue :exec
DELETE FROM venues WHERE id = ?
`

func (q *Queries) DeleteVenue(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVenue, id)
	return err
}

const getVenue = `-- name: GetVenue :one
SELECT id, city, stadium, lat, lon, created_at, updated_at
FROM venues
WHERE id = ?
`

func (q *Queries) GetVenue(ctx context.Context, id int64) (Venue, error) {
	row := q.db.QueryRowContext(ctx, getVenue, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.City,
		&i.Stadium,
		&i.Lat,
		&i.Lon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVenues = `-- name: ListVenues :many
SELECT id, city, stadium, lat, lon, created_at, updated_at
FROM venues
ORDER BY city
`

func (q *Queries) ListVenues(ctx context.Context) ([]Venue, error) {
	rows, err := q.db.QueryContext(ctx, listVenues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.City,
			&i.Stadium,
			&i.Lat,
			&i.Lon,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVenue = `-- name: UpdateVenue :exec
UPDATE venues
SET city = ?, stadium = ?, lat = ?, lon = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateVenueParams struct {
	City    string
	Stadium string
	Lat     float64
	Lon     float64
	ID      int64
}

func (q *Queries) UpdateVenue(ctx context.Context, arg UpdateVenueParams) error {
	_, err := q.db.ExecContext(ctx, updateVenue,
		arg.City,
		arg.Stadium,
		arg.Lat,
		arg.Lon,
		arg.ID,
	)
	return err
}

const updateVenueCoords = `-- name: UpdateVenueCoords :exec
UPDATE venues
SET lat = ?, lon = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateVenueCoordsParams struct {
	Lat float64
	Lon float64
	ID  int64
}

func (q *Queries) UpdateVenueCoords(ctx context.Context, arg UpdateVenueCoordsParams) error {
	_, err := q.db.ExecContext(ctx, updateVenueCoords, arg.Lat, arg.Lon, arg.ID)
	return err
}
