services:
  referee-dashboard:
    image: referee-dashboard
    container_name: referee-dashboard
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/referee-dashboard:/data
    environment:
      - DB_PATH=/data/referee.db
      - PORT=3000
      - SECRET_KEY=${SECRET_KEY}
