INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('GFL','GFL',10,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('GFL2','GFL2',200,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('GFL-Women','GFL W',300,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('GFL2-Women','GFL2 W',400,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('Regionalliga','RL',500,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('Oberliga','OL',600,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('Landesliga','LL',700,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('Bezirksliga','BL',800,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('Kreisoberliga','KOL',900,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('Kreisliga','KL',1000,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('Aufbauliga','AL',1100,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('Aufbauliga Damen','AL W',1200,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('GFL Juniors','GFL J',1300,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('U19 Regionalliga','U19 RL',1400,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('U19 Landesliga','U19 LL',1500,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('U19 Bezirksliga','U19 BL',1600,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('U17 Regionalliga','U17 RL',1700,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('U17 Landesliga','U17 LL',1800,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('U17 Bezirksliga','U17 BL',1900,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('U16 Regionalliga','U16 RL',2000,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('U15 Flag Landesliga','U15 F LL',2100,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('U15 Flag Aufbauliga 5er','U15 F AL (5er)',2200,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('U15 Flag Indoor','U15 F IN',2300,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('U13 Landesliga (Hessen)','U13 LL (HE)',2400,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('U13 Flag Aufbauliga 5er','U13 F AL (5er)',2500,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('U11 Flag Aufbauliga 5er','U11 F AL (5er)',2600,'');
INSERT INTO leagues(name,short_name,sorter,remarks) VALUES('Unbekannt','#NV',10000,'');
