INSERT INTO teams(name,state,is_active,remarks) VALUES('Aalen Legions','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Albershausen Crusaders','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Albstadt Alligators','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Allgäu Commets','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Alzey Lions','Rheinland-Pfalz',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Backnang Wolverines','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Bad Homburg Sentinels','Hessen',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Bad Mergentheim Wolfpack','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Badener Greifs','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Balingen Bucks','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Berlin Kobras','Berlin',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Biberach Beavers','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Bondorf Bulls','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Bretten Black Panthers','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Bruchsal Rebels','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Bürstadt Redskins','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Cologne Crocodiles','Nordrhein-Westfalen',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Crailsheim Praetorians','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Diverse','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Eppelheim Jaguars','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Esslingen Racoons','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Fellbach Warriors','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Freiburg Sacristans','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Fursty Razorbacks','Bayern',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Gießen Golden Dragons','Hessen',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Harthausen Mustangs','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Hassloch 8-Balls','Rheinland-Pfalz',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Heidelberg Hunters','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Heilbronn Salt Miners','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Hellenstein Rascals','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Herrenberg Raptors','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Holzgerlingen Twister','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('KIT SC Engineers','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Kaiserslautern Pikes','Rheinland-Pfalz',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Kirchdorf Wildcats','Bayern',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Konstanz Pirates','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Kornwestheim Cougars','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Kuchen Mammuts','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Kurpfalz Bears','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Leonberg Alligators','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Leonberg Alligators 2','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Ludwigsburg Bulldogs','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Mainz Golden Eagles','Rheinland-Pfalz',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Mannheim Bandits','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Mannheim Bandits 2','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Montabaur Fighting Farmers','Rheinland-Pfalz',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Munich Cowboys','Bayern',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Neckar Hammers','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Newtown Lions','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Nordbaden Dukes','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Pforzheim Wilddogs','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Pforzheim Wilddogs 2','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Ravensburg Razorbacks','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Ravensburg Razorbacks 2','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Regensburg Phoenix','Bayern',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Rettigheim Rhinos','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Reutlingen Eagles','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Reutlingen Eagles 2','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Riedlingen Storks','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Rüsselsheim Crusaders','Hessen',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Schwäbisch Hall Unicorns','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Schwäbisch Hall Unicorns 2','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Stuttgart Scorpions','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('TFG Typhoons','Nordrhein-Westfalen',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Tauberfranken Wolfpack','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Trier Stampers','Rheinland-Pfalz',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Tübingen Red Knights','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Unbekannt','Baden-Württemberg',0,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Walldürn Silverbacks','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Weinheim Longhorns','Baden-Württemberg',1,'');
INSERT INTO teams(name,state,is_active,remarks) VALUES('Wiesbaden Phantoms','Hessen',1,'');
